### ISSUE TITLE
Fail to build with --library-types=static-pic

### ISSUE THREAD

**Issue by timlag1305** [AdaCore/langkit#452]
I am building langkit on Linux using the following command:

`python manage.py build-langkit-support --library-types=static-pic`

I get the following linking error:

```
/usr/bin/ld: -r and -pie may not be used together
collect2: error: ld returned 1 exit status
gprlib: call to linker driver /usr/bin/gcc failed
gprbuild: could not build library for project langkit_support
Traceback (most recent call last):
  File "/home/tim/projects/aur/ada_language_server/src/langkit/manage.py", line 291, in <module>
    args.func(args, unknown_args)
  File "/home/tim/projects/aur/ada_language_server/src/langkit/manage.py", line 87, in wrapper
    fn(args)
  File "/home/tim/projects/aur/ada_language_server/src/langkit/manage.py", line 118, in build_langkit_support
    subprocess.check_call(base_argv + [f"-XLIBRARY_TYPE={library_type}"])
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gprbuild', '-P', '/home/tim/projects/aur/ada_language_server/src/langkit/support/langkit_support.gpr', '-p', '-j16', '-XBUILD_MODE=dev', '-XLIBRARY_TYPE=static-pic']' returned non-zero exit status 4.
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by pmderodat** [comment]
Hello,

This should be due to an issue in GPRbuild/GPRconfig, which we fixed in https://github.com/AdaCore/gprconfig_kb/commit/4863a2068e3cdacfe8b225386772ec3508e4f0b7
Please let us know if this still does not work with that patch, thanks!
